remote_theme: just-the-docs/just-the-docs
title: Structured Rapid Development
logo: './logo.png'
description: Design Patterns to Streamline Learning Design and Development
aux_links:
  "Request a Pattern":
    - "https://github.com/Standards-and-Practices/structured-rapid-development/issues/new?assignees=&labels=enhancement&template=pattern-request.md&title="
  "Report a Bug":
    - "https://github.com/Standards-and-Practices/structured-rapid-development/issues/new?assignees=&labels=bug&template=01_BUG_REPORT.md&title=bug%3A+"
  "Ask a Question":
    - "https://github.com/Standards-and-Practices/structured-rapid-development/discussions"
  "Share an Example":
    - "https://github.com/Standards-and-Practices/structured-rapid-development/issues/new?assignees=&labels=documentation&template=example-submission.md&title=Example+of+%5Byour+pattern+here%5D"